dataset: cifar10
dataroot: './'
download: True
augment: False
hidden_channels: 512
K: 32
L: 3
actnorm_scale: 1.0
flow_permutation: invconv # ["invconv", "shuffle", "reverse"]
flow_coupling: affine  # choices=["additive", "affine"]
LU_decomposed: False
learn_top: False
y_condition: False
y_weight: 0.01 # "Weight for class condition loss"
max_grad_clip: 0 # "Max gradient value (clip above - for off)"
max_grad_norm: 0 # "Max norm of gradient (clip above - 0 for off)"
n_workers: 6 # "number of data loading workers"
batch_size: 64 # "batch size used during training"
eval_batch_size: 512 # "batch size used during evaluation"
epochs: 250 # "number of epochs to train for"
lr: 5e-5
warmup: 5 # "Use this number of epochs to warmup learning rate linearly from zero to learning rate"
n_init_batches: 8  # "Number of batches to use for Act Norm initialisation"
cuda: True
output_dir: "output/"
fresh: True # "Remove output directory before starting"
saved_model: "" # "Path to model to load for continuing training"
saved_optimizer: "" #"Path to optimizer to load for continuing training"
seed: 0
